version: '3.8'


services:
  # server:
  #   build: .
  #   expose:
  #     - ${PORT}
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "3333:3333"
  #   depends_on:
  #     - postgresql
  #     - redis
  #   command: sh -c "node ace migration:run && node bin/server.js"
  #   networks:
  #     - backend

  redis:
    image: redis:latest 
    container_name: redis
    expose:
      - 6379
    ports:
      - 6379:6379
    restart: always
    networks:
      - backend
    # command: redis-server --bind 0.0.0.0 --appendonly yes

  postgresql:
    image: postgres:16.1
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgdata:
  
networks:
  backend:
    driver: bridge

