version: '3.8'

services:
  server:
    build: .
    expose:
      - ${PORT}
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgresql
      - redis
    command: sh -c "node ace migration:run && node bin/server.js"
    networks:
      - backend

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    hostname: 
      - ${REDIS_HOST}
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  postgresql:
    image: postgres:16.1
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
