version: '3.8'
services:
  dev-db-adonis:
    image: postgres:16.1
    container_name: dev-db-adonis
    hostname: dev-db-adonis
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: learningadonis
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
    hostname: redis
    restart: always
    