version: '3.8'


services:
  server:
    build: .
    expose:
      - ${PORT}
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgresql
      - redis-server
    external_links:
      - redis-server
    command: sh -c "node ace migration:run && node bin/server.js"
    networks:
      - backend

  redis-server:
    image: redis:latest 
    container_name: redis-server
    expose:
      - 6379
    restart: always
    networks:
      - backend
    command: redis-server --bind 0.0.0.0 --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  postgresql:
    image: postgres:16.1
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgdata:
  

networks:
  backend:
    driver: bridge

